# Generated by Django 3.2.15 on 2022-09-09 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220909_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
