# Generated by Django 3.2.15 on 2023-05-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_password_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='site_name',
            field=models.CharField(blank=True, default='Site', max_length=500, null=True),
        ),
    ]
